url: https://eicug.github.io
baseurl: /
collections:
  content:
    output: true
    permalink: /content/:title.html

plugins:
  - jekyll-ical-tag

HR: '<hr style="height:8px;border:none;color:#999;background-color:coral;" />'

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
